config/routes.rb
Rails.application.routes.draw do
  # get('/', { to: 'welcome#index'})
  # root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get('/', { to: 'posts#index', as: :home })

       resource :session, only: [:new, :create, :destroy]
     resources :users, only: [:new, :show, :create]
     resources :posts , only: [:index, :new, :show ,:create] do
         resources :comments, only: [:index, :new, :create]
     end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post, dependent: :nullify
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user, optional: true

  has_many :comments,  dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :post,  dependent: :nullify
  has_many :comment, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def user_signed_in?
    # The following is to prevent the app from crashing if we have
    # a user_id in the session and no corresponding user with that id in the db.
    # This occurs when a logged in user is deleted.
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  # The `helper_method` method makes a method available in all views. It effectively
  # turns into a helper method.
  helper_method :current_user

  def authenticate_user!
    if !user_signed_in?
      redirect_to new_session_path, notice: 'Please sign in!'
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
      @post = Post.find params[:post_id]
      @comment =  Comment.new comment_params
      @comment.post = @post
      if @comment.save
        redirect_to post_path(@post)
      end
    end


    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, only: [:create]
  def index
   @posts = Post.order("created_at desc")
   @mostlike = Post.last
   end

   def show
      @comment = Comment.new
      @post = Post.find params[:id]
      @comments = @post&.comments.order(created_at: :desc)

   end

   def create
    @post = Post.new post_params
     if @post.save
      redirect_to posts_path, alert: "you save"
    else
      redirect_to new_post_path, alert: "no save!"
     end
   end

   def new
     @post = Post.new
     @categories = Category.all
   end

   private
   def post_params
     params.require(:post).permit(:title, :body, :category_id)
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email])
     if user #&.authenticate(params[:session][:password])
       session[:user_id] = user.id
       redirect_to home_path, notice: 'Thank you for signing in! ❤️'
     else
       flash.now[:alert] = 'Wrong email or password!'
       render :new
     end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: 'Signed out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user =  User.new user_params

    if @user.save
      # If the user is successfuly created, immediately store their id in the
      # session hash effectively signing them in.
      session[:user_id] = @user.id
      # The flash is temporary that will last until the next
      # request ends. We typically use it to store information
      # to display to the user about what just happened.

      # flash[:notice] = 'Thank you for signing up!'
      # When using `redirect_to`, we can include the flash as an argument
      # instead of writing in a single as above 👆
      redirect_to home_path, notice: 'Thank you for signing up!'
    else
      # Sometimes we want the flash message to appear in the current request and
      # not the next one. User `flash.now[...]` in that situation.
      flash.now[:alert] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Amir</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
     <!-- NavBar -->
         <nav class="navbar navbar-inverse navbar-fixed-top">
           <div class="container-fluid">
             <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
               </button>
                 <% if user_signed_in? %>
               <a class="navbar-brand" href="#">Blog Codecore Hi <%= current_user.first_name %> </a>
                <% else %>
                 <a class="navbar-brand" href="#">Blog Codecore Hi Visitor </a>
                <% end %>
             </div>
             <div class="collapse navbar-collapse" id="myNavbar">
             <ul class="nav navbar-nav">
               <!-- <li class="active"><a href="#">Home</a></li> -->
               <li><a href="#">About</a></li>
               <li><a href="#">Contact</a></li>

             </ul>
             <ul class="nav navbar-nav navbar-right">
               <form class="navbar-form navbar-left">
                 <div class="input-group">
                   <input type="text" class="form-control" placeholder="Search">
                   <div class="input-group-btn">
                     <button class="btn btn-default" type="submit">
                       <i class="glyphicon glyphicon-search"></i>
                     </button>
                   </div>
                 </div>
               </form>

                <% if user_signed_in? %>
               <li><%= link_to 'Sign Out', session_path, method: :delete %></li>

               <li><%= link_to 'Create Post', new_post_path %></li>
               <% else %>
                <li><%= link_to 'Sign Up',  new_user_path %></li>

               <li><%= link_to 'Login', new_session_path %></li>
               <% end %>

             </ul>
           </div>
         </div>
       </nav>
      <!-- End of NavBar -->
      <br> <br><br> <br><br> <br>
   <!--  -->

    <div> <%= flash[:notice] %></div>
    <div> <%= flash[:alert] %> <div>

  <body>
  
    <%= yield %>
  </body>
<div class="col-md-3"> </div>
<div class="col-md-1">
        <a href="https://www.facebook.com/bootsnipp"><i class="fa fa-facebook-square fa-5x social"></i></a>
</div>
<div class="col-md-1">
         <a href="https://twitter.com/bootsnipp"><i class="fa fa-twitter-square fa-5x social"></i></a>
</div>
<div class="col-md-1">
         <a href="https://plus.google.com/+Bootsnipp-page"><i class="fa fa-google-plus-square fa-5x social"></i></a>
</div>
<div class="col-md-1">
         <a href="mailto:bootsnipp@gmail.com"><i class="fa fa-envelope-square fa-5x social"></i></a></div>
</div>
<div class="col-md-1">
         <a href="mailto:bootsnipp@gmail.com"><i class="fa fa-camera fa-5x social"></i></a></div>
</div>
<div class="col-md-4"> </div>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">

<style>
 /*.more {
   display: none;
 }
 .show {
   display: block;
 }*/
 .row.equal {
     display: flex;
     flex-wrap: wrap;
   }

   #cell {

       height: 150px;
       border: 1px solid white;
       display: -webkit-flex; /* Safari */
       display: flex;
   }
/*.bud {
     display:none;
 }*/
   .bud:nth-of-type(7) ~ .bud {
     /*display:none;*/
     display: none;
 }

 .showall{
   display: block;
 }
 .hide{
   display: none;
 }
  .fa-heart {
    color: pink;
  }

</style>

<script>


// differenct between var i of array and var i in array 😘
// flux keep height of box fixed 😗
//  .bud:nth-of-type(7) ~ .bud { keep first 8 elements show 😚

function my(){
 a =  document.getElementsByClassName("bud")
 for (var i of a) {

   i.className += 'showall';
}
 document.getElementById("showmore").className += 'hide';

}

</script>
<body class="containre">

  <div class="row">
     <div class="col-md-8">
         <%= image_tag("https://www.axure.com/c/attachments/forum/7-0-general-discussion/3919d1401387174-turn-placeholder-widget-into-image-maintain-interactions-screen-shot-2014-05-29-10.46.57-am.png", size: "400x20" , class: "img-responsive") %>

       <%= fa_icon "heart", class: "fa-3x" %>
        433 <%= %>
       <h3>

       </h3>
       <p>
  
         <%= @mostlike.body %>

       </p>
     </div>
     <div class="col-md-4 ">
      <h3> Most Like </h3>
      <p> Infrastructure-wise everything was there: there was a mailing list,
there was a website, there was source code control (CVS). But there
was no actual code for people to work on. The only things I had
were some ideas of what I wanted to do, an itch to scratch and the
right buzzwords. I actually wanted people to join in creating this
program and make it a truly collaborative project.</p>
     </div>
   </div>

   <% cnt = 0 %>
     <% @posts.each { |f|  %>
    <div class="bud">
      <div class="col-md-4 col-xs-12">

        <%= image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU2HkgGsdwaUOVECPqgTjrQxIafigiPHEz5yeoGLapWVPhzsxGZw" , size: "350x100" , class: "img-responsive") %>

        <%= fa_icon "heart", class: "fa-3x" %>
          433 <%= %>
        <h4>
        <%= link_to f.title, post_path(f) %>
        </h4>
        <p id="cell"> <%= f.body %> </p>
      </div>
    </div>
  <!--  -->
    <%  } %>

  <div class="col-md-12"><br></div>



    <div class="col-md-4"></div>
    <div class="col-md-4">
      <button id="showmore" onclick="my()">Show more</button>

    </div>
    <div class="col-md-4"></div>
</body>
</html>

app/views/posts/new.html.erb
<div class="container">
<h1> Create Post </h1>
<%= bootstrap_form_for(@post) do |f| %>
  <%= f.select(:category_id) do %>
    <% @categories.each do |c| -%>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>
  <%= f.text_field :title %>
  <%= f.text_field :body %>
  <%= f.submit "Create Post" %>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h1><%= @post.title %></h1>
     <p><%= @post.body %></p>

    <%= bootstrap_form_for [@post, @comment] do |f| %>
      <%= f.text_field :body %>
      <%= f.submit "comment" %>
  <% end %>

  <div class="container">
    <% @comments.each do |f| %>
    <div class="col-md-12">
    <%= f.body %>
   </div>
    <% end %>
  </div>

</div>

app/views/users/new.html.erb
<h1> Create New User </h1>


<%= simple_form_for @user do |f| %>
<%=  f.input :first_name %>
<%=  f.input :last_name %>
<%=  f.input :email %>
<%=  f.input :password %>
<%=  f.button :submit %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>